# Generated by Django 3.2.14 on 2022-07-21 21:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(default=None, max_length=200)),
                ('created_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(default=None, max_length=200)),
                ('sets_count', models.PositiveIntegerField(default=0)),
                ('reps_count', models.PositiveIntegerField(default=0)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('tr_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainscreen.post')),
            ],
        ),
    ]
