# Generated by Django 3.2.14 on 2022-07-11 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainscreen', '0002_auto_20220712_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
