# Generated by Django 3.2.14 on 2022-07-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainscreen', '0003_remove_post_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='set',
            new_name='sets_count',
        ),
    ]
