# Generated by Django 3.2.14 on 2022-07-24 22:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainscreen', '0004_alter_note_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_text',
            field=models.TextField(default=None, max_length=400),
        ),
    ]
