# Generated by Django 3.2.14 on 2022-07-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainscreen', '0005_auto_20220725_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_text',
            field=models.TextField(default=None),
        ),
    ]
