# Generated by Django 3.2.14 on 2022-07-14 16:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainscreen', '0006_alter_post_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=200)),
                ('created_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='training_name',
        ),
        migrations.AddField(
            model_name='post',
            name='training',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainscreen.trainingdate'),
            preserve_default=False,
        ),
    ]
