# Generated by Django 3.2.14 on 2022-07-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainscreen', '0006_alter_note_note_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_tonnage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
