# Generated by Django 3.2.14 on 2022-07-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainscreen', '0007_auto_20220714_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='training',
        ),
    ]
