# Generated by Django 3.2.14 on 2022-08-14 22:34

from django.db import migrations, models
import django.utils.timezone
import mainscreen.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainscreen', '0008_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='photo',
            name='im_photo',
            field=models.ImageField(upload_to=mainscreen.models.upload_file_path),
        ),
    ]
