# Generated by Django 3.2.14 on 2022-07-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainscreen', '0008_remove_post_training'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingDate',
        ),
        migrations.AddField(
            model_name='post',
            name='training_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
