# Generated by Django 3.2.14 on 2022-08-17 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainscreen', '0009_auto_20220815_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Training'},
        ),
    ]
