# Generated by Django 3.2.14 on 2022-07-14 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainscreen', '0010_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
    ]
