# Generated by Django 3.2.14 on 2022-07-14 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainscreen', '0011_delete_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reps_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sets_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='weight',
        ),
    ]
