# Generated by Django 3.2.14 on 2022-09-01 19:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainscreen', '0013_auto_20220901_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200)),
                ('value', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('chart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainscreen.chart')),
            ],
        ),
    ]
