# Generated by Django 3.2.14 on 2022-09-01 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainscreen', '0014_chartdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartdata',
            name='title',
        ),
    ]
