# Generated by Django 3.2.14 on 2022-09-01 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainscreen', '0015_remove_chartdata_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chartdata',
            old_name='chart',
            new_name='chart_pk',
        ),
    ]
